name: Build and Publish Docker hub
  on: [push]
    jobs:
      build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Publish to Docker hub
          uses: elgohr/Publish-Docker-Github-Action@v5
          with:
            name: ispeakcode/docker-githubaction
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }} 